[theme]
primaryColor = "#16A34A"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
runOnSave = true
headless = true

[browser]
gatherUsageStats = false
